- name: working with shell and command module
  hosts: localhost
  connection: local
  tasks:
    - name: command module
      #ansible.builtin.command: cat etc/passwd | grep root
      ansible.builtin.shell: mkdir folder
      register: useroutput 
    - name: output is 
      ansible.builtin.debug:
       msg: "{{useroutput}}"